apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "traccar.fullname" . }}
  labels:
    {{- include "traccar.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "traccar.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}
      labels:
        {{- include "traccar.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "traccar.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "traccar.fullname" . }}
{{- if .Values.mysql.enabled }}
      initContainers:
        - name: wait-for-db
          image: "alpine:3.16"
          command:
            - 'sh'
            - '-c'
            - >
              until nc -z -w 2 {{ include "traccar.fullname" . }}-mysql 3306 && echo mysql ok;
                do sleep 2;
              done
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["java", "-Xms512m", "-Xmx512m", "-Djava.net.preferIPv4Stack=true"]
          args: ["-jar", "tracker-server.jar", "conf/traccar.xml"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
{{- range $item := .Values.externalService.protocolPorts }}
            - name: {{ $item.name }}
              containerPort: {{ $item.port }}
              protocol: TCP
{{- end }}
          livenessProbe:
            httpGet:
              path: /api/server
              port: http
            initialDelaySeconds: 60
            periodSeconds: 60
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /api/server?force=true
              port: http
            initialDelaySeconds: 60
            periodSeconds: 60
            failureThreshold: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: "config"
            subPath: "traccar.xml"
            mountPath: "/opt/traccar/conf/traccar.xml"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
