{{- if not .Values.configOverride }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "traccar.fullname" . }}
  labels:
    {{- include "traccar.labels" . | nindent 4 }}
stringData:
  {{- if .Values.mysql.enabled }}
  DATABASE_USER: {{ .Values.mysql.auth.username | quote }}
  DATABASE_PASSWORD: {{ .Values.mysql.auth.password | quote }}
  {{- else }}
  {{- if ((.Values.traccar).database).user }}
  DATABASE_USER: {{ .Values.traccar.database.user | quote }}
  {{- end }}
  {{- if ((.Values.traccar).database).password }}
  DATABASE_PASSWORD: {{ .Values.traccar.database.password | quote }}
  {{- end }}
  {{- end }} {{/* end if mysql.enabled */}}
  {{- if (((.Values.traccar).mail).smtp).username }}
  MAIL_SMTP_USERNAME: {{ .Values.traccar.mail.smtp.username | quote }}
  {{- end }}
  {{- if (((.Values.traccar).mail).smtp).password }}
  MAIL_SMTP_PASSWORD: {{ .Values.traccar.mail.smtp.password | quote }}
  {{- end }}
{{- end }}
